version: 2

sources:
  - name: silver
    catalog: silver_catalog
    schema: silver_sch

    tables:
      - name: silver_customers
      - name: silver_orders
      - name: silver_order_payments
      - name: silver_products
      - name: silver_product_categories
      - name: silver_sellers
      - name: silver_sales